### ISSUE TITLE
Email Notification > Multiple notification

### ISSUE THREAD

**Issue by Horttcore** [awsmug/torro-forms#410] opened 2018-04-21 20:48 UTC
The backend form buttons don't work if there are more then 1 notification.

![image](https://user-images.githubusercontent.com/503252/39088641-02c86d00-45b6-11e8-9cd8-bfc7006b45c7.png)

**Comment by felixarntz** [comment] 2018-04-21 21:33
Duplicate of #405. This is already fixed and will be released tomorrow.

**Closed by felixarntz** 2018-04-21 21:33 UTC
Labels: bug, duplicate
