### ISSUE TITLE
Page Ask Confirmation on publishing

### ISSUE THREAD

**Issue by Fecomstore** [awsmug/torro-forms#362] opened 2017-11-18 17:17 UTC
Hi, i'm having this issue with both Torro Forms and the old Questions plugin.

If i create widgets and don't assign any text or content, then i can submit the form.

But, if i add text to a textview, or try to set the content of any of the widgets, the following happens:

When i click on Publish, or Save Draft, the page shows me the alert:
"The page is asking you to that you want to leave.." with the two buttons "Stay on Page" and "Leave"

If i click "Leave Page" everything goes fine and the form is created and published.
If i click "Stay on Page", The publish button is disabled and the spinner next to it spins forever.

**Comment by mahype** [comment] 2017-11-20 14:43
Hi,

sorry, but I do net get what you want. In need some more information. I don’t know what the widgets have to do with the Admin page, because you do not have widgets within the forms Admin area. Can you please try to describe a bit more detailed?

That would be great!

Thank you!

Sven

**Comment by Fecomstore** [comment] 2017-11-21 01:41
For "widget" i mean the views (TextBox, Checklist, TextView ecc..) that Questions and Torro Forms provide in the edit_post page.

When i go to the edit_post page and i try to create a new survey(Questions) or a new form( Torro Forms ), in both cases i get the error described above.
For example, If I drag and drop a textview and  don't set the title, i can publish the survey/form with no problems.
But if i try to set the title of the textview, or fill the values of a checklist and then click to Publish, Firefox and chrome warnings me with: "The page is asking you to that you want to leave.."

I have currently installed wordpress 4.9.
Even if I get this behaviour on both Questions and Torro Forms,I would really like to keep using Questions, so if you manage to find what the problem is, can you tell me where the pitfall is so i can fix it in the Questions plugin?

**Comment by mahype** [comment] 2017-11-21 14:38
Aaaah! I got it now. I tried and reproduced it. 

I am very sorry to say, but we unfortunately won't fix that bug anymore. We are working on Torro Forms in the next version since more than a year since version beta 8 and we have totally rebuilt it that we have a lot more reliable base for the future. 

In the coming version we won't have this problem anymore, I have tried it now with our developing version and it works.

I am very sorry to say that, but you have to wait for the next version we will release in the beginning of the new year, but as I have seen, if you save the form and you click on "leave", the form will still be saved.

**Closed by mahype** 2017-11-21 14:38 UTC
