### ISSUE TITLE
WP Editor in Description Element Display Errors

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#39] opened 2015-11-03 17:25 UTC
If I want to size the WP Editor in the Tabs of the Description Element there are some display and handling issues.

- [ ] <del>Editor is crashing on trying to resize it.</del>
- [x] Switching between text and HTML view makes problems
- [x] cannot access visual editor after dragging the element

The Editor seemed to be not initialized correct.

**Comment by felixarntz** [comment] 2016-03-23 18:09
The problem is not resizing of the editor, but dragging the surrounding element.

Before it happened when resizing the editor because dragging the resize button would also trigger dragging the whole element which is not intended. Therefore I disabled this behavior, now it's only possible to drag an element from its `.widget-top` bar.

**Comment by felixarntz** [comment] 2016-03-24 14:52
This was a general bug that even happens in default WordPress Core when you place a WP Editor inside of any draggable container. Fixed now :)

**Closed by felixarntz** 2016-03-24 14:52 UTC
Labels: bug, ready
