### ISSUE TITLE
Notice: Undefined index: & Fatal error: Call to a member function enqueue() on null in 

### ISSUE THREAD

**Issue by alexlii1971** [awsmug/torro-forms#396] opened 2018-04-17 08:43 UTC
Hello，

I download it from  https://wordpress.org/plugins/torro-forms/

Errors will be show up once I click the setting at backend, screenshot:

http://prntscr.com/j6bjmf

Notice: Undefined index: in /var/www/mysite.com/htdocs/wp-content/plugins/torro-forms/vendor/felixarntz/plugin-lib/src/components/tabbed-settings-page.php on line 165

Fatal error: Call to a member function enqueue() on null in /var/www/mysite.com/htdocs/wp-content/plugins/torro-forms/vendor/felixarntz/plugin-lib/src/components/tabbed-settings-page.php on line 165

I test it in a subsite:

Server info: |   | nginx/1.10.0
-- | -- | --
PHP version: |   | 5.6.33-0+deb8u1
WP version: |   | 4.9.4
-- | -- | --
WP multisite: |  yes |  
WP memory limit: |   | 256 MB
WP debug mode: |  yes |  

Alex

**Comment by mahype** [comment] 2018-04-17 08:52
Hi Alex,

we have to check an to reproduce that and will come back to you! Thank you for your information.

Sven

**Comment by alexlii1971** [comment] 2018-04-17 14:35
I test it after I reset a subsite, which is fresh installation, a redis  cache and buddypress, Multisite auth plugin are networkly activated.

As to stack trace,  I suppose you need check by console,  please write to me alexlii at yahoo dot com, I will send you a administrator account for your check, is that ok?

Thanks

Alex

**Comment by alexlii1971** [comment] 2018-04-17 15:56
Do you think it is a good way for you remotely check php stack trace by useing this plugin: https://wordpress.org/plugins/wp-php-console/

If yes, just please let me know.

Alex

**Comment by alexlii1971** [comment] 2018-04-19 07:34
@mahype and @felixarntz 

Would you please let me know where I can download the previous version? so that I can make my site work at least before this issue is fixed.


thanks.

Alex

**Comment by tyrann0us** [comment] 2018-04-19 08:51
http://wpengineer.com/2813/update-download-older-plugin-versions-from-wordpress-org/

**Comment by felixarntz** [comment] 2018-04-21 20:35
I believe this happened because the `$tabs` property of the class was looped through, and it was not reset afterwards. A hardened check should prevent this. Fixed via https://github.com/felixarntz/plugin-lib/commit/37be11f5350ca8edfbfc6e9f0f8e33ba1cfd665a

Please reopen this issue if the issue still persists after the next Torro Forms beta release.

**Closed by felixarntz** 2018-04-21 20:35 UTC
Labels: bug

**Comment by alexlii1971** [comment] 2018-04-23 07:18
Yes, great, it was fixed:

http://prntscr.com/j8uvno

Alex
