### ISSUE TITLE
Email Notifications > Placeholder was not replaced

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#407] opened 2018-04-20 07:11 UTC
I tried to send an email via form. The {sitetitle} placeholder was not replaced.

<img width="622" alt="bildschirmfoto 2018-04-20 um 09 09 26" src="https://user-images.githubusercontent.com/663697/39035572-ca541b54-447a-11e8-88dd-b7e6594f372d.png">

**Comment by felixarntz** [comment] 2018-04-21 20:49
Duplicate of #395

**Closed by felixarntz** 2018-04-21 20:49 UTC
Labels: bug, duplicate
