### ISSUE TITLE
Updates to the form is not reflecting

### ISSUE THREAD

**Issue by kai-kai0** [awsmug/torro-forms#456] opened 2018-07-17 08:01 UTC
## Issue Overview
I've added new pages and questions, however, I can't seem to add new questions, pages, page redirection and even email notification thereafter. 

Each time after I've added new questions, configured the settings for email notification etc, I clicked on Update and the page refreshed and still showing the old settings-my new configuration and questions are not captured and reflected. 

## Expected Behavior
The changes should be reflected upon updating form.

## Current Behavior
After pressing on update, new changes or addition of questions are not showing.

**Comment by mahype** [comment] 2018-07-17 08:23
Hello Kai,

thank you for reporting. We will check this behavior. But first can you please tell us, which WP and Plugin version do you use? 

Kind regards,

Sven

**Comment by mahype** [comment] 2018-07-26 17:03
Hi Kai,

I have checked this but I can not reproduce it. Do you have the possibility to see if your browser console is showing Javascript errors? Otherwise I have to take a look at your site if this is possible. You can send me the data to my mail address if you dont want to show it in public.

Kind regards,

Sven

**Comment by kai-kai0** [comment] 2018-07-27 01:33
Hi Sven,

I’ve attached a video of the error reproduction done on Google Chrome in the link below.

https://we.tl/XwmfRcYzCT <https://we.tl/XwmfRcYzCT>


Please advise. Thank you.



Regards,
Kai

**Comment by mahype** [comment] 2018-07-30 08:42
Hi Kai,

thank you for that video. Would be possible to switch off all other plugins and to activate a standard theme that we can exclude a conflict with it. I have the problem that I can not reproduce the error. I need to reproduce it to fix the bug.

Greetings,

Sven

**Comment by mahype** [comment] 2018-07-30 08:56
Another approach could be a server setting: Can you delete an existant question and check if you can add a new one? Maybe the max_input_vars setting in your PHP settings is too low. If this is the problem we need to add a message which helps the user in that case.

**Comment by felixarntz** [comment] 2018-08-21 17:25
@kai-kai0 Version 1.0.1 will introduce proper error handling, so hopefully this will make it easier to replicate your issue. Can you try again with Torro Forms version 1.0.1 and share the feedback the plugin provides?

**Comment by mahype** [comment] 2018-11-08 20:06
I will close this ticket, because of no feedback.

**Closed by mahype** 2018-11-08 20:06 UTC
Labels: waiting for feedback
