### ISSUE TITLE
Adding the possibility to show results before sending

### ISSUE THREAD

**Issue by mahype** [awsmug/torro-forms#327] opened 2016-11-14 08:14 UTC
Several people asked for a result summary before sending the form. There should be a possibility to add the answers by shortcode or something.

**Comment by felixarntz** [comment] 2017-10-14 00:01
This is an extra feature and will be worked on after the initial release.

**Comment by felixarntz** [comment] 2018-02-19 22:49
Related: #281

**Comment by felixarntz** [comment] 2018-02-19 23:00
Let's work on this via #388, which is a newer duplicate of this issue.

**Closed by felixarntz** 2018-02-19 23:00 UTC
Labels: enhancement
