### ISSUE TITLE
Email Notification > Using field as recipient

### ISSUE THREAD

**Issue by Horttcore** [awsmug/torro-forms#408] opened 2018-04-21 20:30 UTC
Fatal error: Form 178 Submission 295: Email notification to {value_element_4} could not be sent. Original error message: You must provide at least one recipient email address. in /var/www/vhosts/dhc-vision.com/httpdocs/wp-content/plugins/torro-forms/src/logger.php on line 68

Can't use E-Mail field as email recipient.

**Comment by felixarntz** [comment] 2018-04-21 21:31
This happened because replacing placeholders in email notifications didn't work (i.e. this is a duplicate of #395). It will be fixed in the next beta coming out tomorrow.

**Closed by felixarntz** 2018-04-21 21:31 UTC
Labels: bug, duplicate
